# Web_Elements_Method_Pratical 
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
driver=webdriver.Chrome()
driver.get('https://rahulshettyacademy.com/AutomationPractice/')
driver.maximize_window()
name_box=driver.find_element(By.ID,'autocomplete')
name_box.send_keys('Australia')
time.sleep(2)
name_box.clear()
time.sleep(1)
name_box.send_keys('India')
driver.find_element(By.XPATH,"//input[@value='radio2']").click()
time.sleep(1)
checkbox=driver.find_element(By.XPATH,'/html/body/div[1]/div[4]/fieldset/label[3]/input')
checkbox.click()
time.sleep(1)
heading=driver.find_element(By.TAG_NAME,'h1').text
print(heading)
place_name=name_box.get_attribute('class')
print(place_name)
textbox=driver.find_element(By.ID,'displayed-text')
print('Before hide:',textbox.is_displayed())
driver.find_element(By.ID,'hide-textbox').click()
time.sleep(1)
print('After hide:',textbox.is_displayed())
driver.find_element(By.ID,'show-textbox').click()
time.sleep(1)
print('Textbox enable:',textbox.is_enabled())
print('Checkbox selected:',checkbox.is_selected())
time.sleep(2)
driver.quit()