# Form Validation
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
driver=webdriver.Chrome()
driver.maximize_window()
driver.get("https://demoqa.com")
time.sleep(5)
# driver.find_element(By.XPATH,"//div[@class='card mt-4 top-card']").click()
driver.find_element(By.LINK_TEXT,'Forms').click()
time.sleep(5)
driver.find_element(By.LINK_TEXT,"Practice Form").click()
time.sleep(5)
# Pratice_Form 
first_name=driver.find_element(By.XPATH,"//input[@id='firstName']")
first_name.send_keys('Rajesh')
time.sleep(3)
last_name=driver.find_element(By.XPATH,"//input[@id='lastName']")
last_name.send_keys("Sahoo")
time.sleep(3)
Email=driver.find_element(By.CSS_SELECTOR,"#userEmail")
Email.send_keys('rajeshsahoo@gmail.com')
time.sleep(3)
gender=driver.find_element(By.CSS_SELECTOR,"#gender-radio-1")
gender.click()
time.sleep(3)
mobile=driver.find_element(By.XPATH,"//input[@id='userNumber']")
mobile.send_keys("7684899803")
time.sleep(3)
# subject=driver.find_element(By.CSS_SELECTOR,'.subjects-auto-complete__input-container')
# subject.send_keys("Python")
subject=driver.find_element(By.CSS_SELECTOR,'.subjects-auto-complete__input')
subject.send_keys('Python')
time.sleep(3)
hobbis1=driver.find_element(By.CSS_SELECTOR,'#hobbies-checkbox-1')
hobbis1.click()
# time.sleep(2)
hobbis2=driver.find_element(By.CSS_SELECTOR,'#hobbies-checkbox-2')
hobbis2.click()
# time.sleep(2)
hobbis3=driver.find_element(By.CSS_SELECTOR,'#hobbies-checkbox-3')
hobbis3.click()
time.sleep(3)
address=driver.find_element(By.CSS_SELECTOR,'#currentAddress')
address.send_keys('Kendrapara')
time.sleep(3)
submit=driver.find_element(By.CSS_SELECTOR,'#submit')
submit.submit()
time.sleep(5)




